language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
  - "pypy3.5"
# For the moment it looks like Python 3.7 requires this workaround
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]] && [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install mypy; fi
script:
  - python test_cuid.py
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]] && [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then mypy cuid.py; fi
